name: Build and deploy Node.js app to Azure Web App - myappblog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Node.js'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 'Install dependencies'
      run: npm install
      working-directory: ./blog-project

    - name: 'Build project'
      run: npm run build
      working-directory: ./blog-project

    - name: 'Upload production-ready build files'
      uses: actions/upload-artifact@v2
      with:
        name: node-build
        path: ./blog-project/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: 'Download build files'
      uses: actions/download-artifact@v2
      with:
        name: node-build
        path: ./blog-project/build

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myappblog'
        slot-name: 'production'
        package: ./blog-project/build
