name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./blog-project

      - name: Build
        run: npm run build
        working-directory: ./blog-project/client

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: node-build
          path: ./blog-project/client/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: node-build
          path: ./blog-project/client/build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: myappblog
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

